apiVersion: batch/v1
kind: Job
metadata:
  name: mlops-train-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: trainer
          image: mlops-pytorch-train:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
            - name: storage-volume
              mountPath: /app/data
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: mlops-config
            items:
              - key: training_config.yaml
                path: training_config.yaml
        - name: storage-volume
          persistentVolumeClaim:
            claimName: mlops-pvc
